// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

const s = 'abcd';
const t = 'abcde';

var findTheDifference = function(s, t) {
    for (var i = 0; i < s.length; i++) {
        t = t.replace(s[i], '');
    }
    return t;
};

const difference = findTheDifference(s, t);
console.log(difference);
